# Use an official OpenJDK runtime as a parent image
FROM openjdk:17-jdk-slim

# Set the working directory in the container
WORKDIR /app

# Copy the frontend JAR file to the container
# Adjust the path based on where your frontend JAR is located
COPY BuymeWebParent/BuymeFrontEnd/target/BuymeFrontEnd-0.0.1-SNAPSHOT.jar app.jar

# Expose the frontend port (e.g., 8080)
EXPOSE 8080

# Run the frontend application
ENTRYPOINT ["java", "-jar", "app.jar"]
