version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: buyme-backend
    volumes:
      # Map host directories to container directories
      - ./brand-logos:/root/Buyme-0.2/brand-logos
      - ./category-images:/root/Buyme-0.2/category-images
      - ./product-images:/root/Buyme-0.2/product-images
      - ./site-logo:/root/Buyme-0.2/site-logo
      - ./user-photos:/root/Buyme-0.2/user-photos
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: buyme-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: prod