version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: buyme-backend
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: buyme-frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
