version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    image: buyme-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    image: buyme-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      SPRING_PROFILES_ACTIVE: prod